### ISSUE TITLE
Suppress debug messages from connection.py

### ISSUE THREAD

**Issue by glassbase** [JeffLIrion/python-androidtv#49]
How can we suppress the spamming of debug messages? 

I used to just comment them out of config/deps/adb_messenger/connection.py but now that the deps folder is no longer used, what can we do?

**Comment by JeffLIrion** [comment]
Please file an issue in the Home Assistant repo. 

In the meantime, this custom component should fix the issue: https://github.com/JeffLIrion/ha-androidtv

**Comment by JeffLIrion** [comment]
@glassbase does that custom component fix the issue?

**Comment by glassbase** [comment]
I am running it but still get the logs. Is there something I need to put in logger.yaml to suppress them?

**Comment by JeffLIrion** [comment]
Are you running the version of the component with this on line 23 of media_player.py?

```python
logging.getLogger('adb_messenger').setLevel(_LOGGER.getEffectiveLevel())
```

**Comment by glassbase** [comment]
Will update to latest version.

**Comment by glassbase** [comment]
I now have latest version with the line you mentioned... still got the messages.

**Comment by JeffLIrion** [comment]
OK, I changed the line to this:

```python
logging.getLogger('adb_messenger').setLevel(logging.CRITICAL)
```

Do you still get the messages?

**Comment by glassbase** [comment]
That worked. Thanks

**Comment by JeffLIrion** [comment]
I made a second change that bumps the version for pure-python-adb, and I think that's what fixed the issue, not the line referenced above. I removed that line just now. Could you let me know if it's still fixed?
